spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/redistest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

logging.level:
  org.hibernate.SQL: info